openapi: 3.0.0
info:
  version: 1.0.0
  title: Imgflip Meme Generator API
  description: |
    The Imgflip API uses a RESTful JSON interface. Request parameters are standard HTTP form urlencoded parameters, and return data is JSON.

    The base version of the API is free. You can upgrade to our Premium API to unlock advanced features. Requests to the free version of the API do not have a hard limit, but may be throttled or blocked if you start doing crazy things or abusing the API. The Premium API has a base cost of $9.99 per month and includes some Premium requests each month (details below). After that, each type of Premium request has a small per-request cost. Note that the free API endpoints are still free if you have API Premium, you'll only be charged for the Premium-only features.

    Feel free to contact us at general@imgflip.com with any questions or suggestions. 

servers:
  - url: https://api.imgflip.com
    description: Default server

security:
  - BasicAuth: [] # use the same name as under #/securitySchemes

paths:
  /get_memes:
    get:
      description: Gets an array of popular memes that may be captioned with this API. The size of this array and the order of memes may change at any time. When this description was written, it returned 100 memes ordered by how many times they were captioned in the last 30 days. Additional properties other than those listed below may be added in the future without warning, so do not assume the JSON structure of each meme will never have new properties.
      responses:
        "200":
          description: OK - The request was successfull.
          content:
            application/json:
              schema:
                success:
                  type: boolean
                  description: Returns `true` when the request is successfull.
                data:
                  type: object
                  description: Returns an object containing `memes`, which is the array of the popuplar memes.
                  properties:
                    memes:
                      type: array
                      description: Returns an array of the popular memes.
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                            description: Unique identifier (ID) for the meme template. This ID is needed to caption memes using the `/caption_memes` endpoint.
                            example: "61579"
                          name:
                            type: string
                            description: Name of the meme template.
                            example: "One Does Not Simply"
                          url:
                            type: string
                            description: URL of the image used in the meme template.
                            example: "https://i.imgflip.com/1bij.jpg"
                          width:
                            type: integer
                            description: Width of the template's image, in pixels.
                            example: 568
                          height:
                            type: integer
                            description: Height of the template's image, in pixels.
                            example: 335
                          box_count:
                            type: integer
                            description: Number of editable text boxes for the meme template.
                            example: 2
        default:
          description: Unexpected error
    post:
      description: |
        This is a **fake** method for testing the API documentation parser. This API does NOT have a `POST` method.
      requestBody:
        description: This is a **fake** body request. It does not exist in this API.
        required: true
        content:
          application/json:
            schema:
              bogus_1:
                description: This is a **fake** body parameter. It does not exist in this API.
                required: true
                type: string
              bogus_2:
                description: This is another **fake** body parameter. It does not exist in this API.
                required: false
                type: string

  /caption_image:
    post:
      description: |
        Adds a caption to an Imgflip meme template. Images created with this API will be publicly accessible by anyone through the url in the response - there is no "private" option. This does not mean these memes will be posted publicly though, one still needs to know the exact URL to find the image. If the image hangs around on Imgflip servers for a while and gets very few views (direct image views and image page views both count), it will be auto-deleted to save space.
        
        For a real working example of the API, check out this hubot script (written in coffeescript). That script is open source, so feel free to use that set of regexes as a starting place.
        
        IMPORTANT NOTE: If you plan to use the API for anything other than testing, you should create your own Imgflip account and use that instead of the default imgflip_hubot account, because that account may be limited as soon as you send a non-trivial number of requests, and then your script wouldn't be able to make memes anymore, and everyone would be sad. All memes on Imgflip can have custom default font settings which will be used if you do not specify the exact settings you want. For example, this allows a meme such as Two Buttons to default to uncapitalized black text with rotation applied, because it fits the template better.
      requestBody:
        description: All memes on Imgflip can have custom default font settings which will be used if you do not specify the exact settings you want. For example, this allows a meme such as Two Buttons to default to uncapitalized black text with rotation applied, because it fits the template better.
        required: true
        content:
          application/json:
            schema:
              template_id:
                description: A template ID as returned by the get_memes response. Any ID that was ever returned from the get_memes response should work for this parameter. For custom template uploads, the template ID can be found in the memegenerator URL, e.g. https://imgflip.com/memegenerator/14859329/Charlie-Sheen-DERP. Also, here is a list of the top 100 Imgflip meme IDs.
                required: true
                type: string
              username:
                description: Username of a valid imgflip account. This is used to track where API requests are coming from.
                required: true
                type: string
              password:
                description: Password for the imgflip account. As always, make sure password (and all the other parameters) are in the body of the POST request, not in the request url.
                required: true
                type: string
              text0:
                description: Top text for the meme (do not use this parameter if you are using the boxes parameter below).
                required: true
                type: string
              text1:
                description: Bottom text for the meme (do not use this parameter if you are using the boxes parameter below).
                required: true
                type: string
              font:
                description: The font family to use for the text. Defaults to impact. You can also use "arial" or any of the 1,500+ Google Fonts which you can see in the font menu at imgflip.com/memegenerator.
                required: false
                type: string
              max_font_size:
                description: Maximum font size in pixels. Defaults to 50px.
                required: false
                type: integer
              no_watermark:
                description: Premium Only - Remove the imgflip.com watermark. First 100 per month included, then $0.01 per creation.
                required: false
                type: boolean
              boxes:
                description: |
                  For creating memes with more than two text boxes, or for further customization. If boxes is specified, text0 and text1 will be ignored, and text will not be automatically converted to uppercase, so you'll have to handle capitalization yourself if you want the standard uppercase meme text. The API is currently limited to 20 text boxes per image. All options below are optional, except "text". The exception is that you may leave the first box completely empty, so that the second box will automatically be used for the bottom text.

                  x, y, width, and height are for the bounding box of the text box. x and y are the coordinates of the top left corner. If you specify bounding coordinates, be sure to specify all four (x, y, width, height), otherwise your text may not show up correctly. If you do not specify bounding box coordinates, the same automatic default coordinates from imgflip.com/memegenerator will be used, which is very useful for memes with special text box positioning other than the simple top/bottom.
                required: false
                type: array
                items:
                  type: object
                  properties:
                    text:
                      type: string
                      description: Text to be added to the text box.
                      example: "One does not simply"
                    x:
                      type: integer
                      description: Horizontal position (X) of the text box.
                      example: 10
                    y:
                      type: integer
                      description: Vertical position (Y) of the text box.
                      example: 10
                    width:
                      type: integer
                      description: Width of the text box.
                      example: 548
                    height:
                      type: integer
                      description: Height of the text box.
                      example: 100
                    color:
                      type: string
                      description: Color of the text.
                      example: "#ffffff"
                    outline_color:
                      type: string
                      description: Outline color of the text.
                      example: "#000000"
      responses:
        "200":
          description: OK - The request was successfull.
          content:
            application/json:
              schema:
                success:
                  type: boolean
                  description: Returns `true` when the request is successfull.
                data:
                  type: object
                  description: |
                    Returns an object containing one URL for the meme image and another URL for the meme template on imgflip.com.
                  properties:
                    url:
                      type: string
                      description: URL for the meme image.
                      example: "https://i.imgflip.com/123abc.jpg"
                    page_url:
                      type: string
                      description: URL for the meme template on imgflip.com.
                      example: "https://imgflip.com/i/123abc"
        default:
          description: Unexpected error

# Basic authentication
components:
  securitySchemes:
    BasicAuth:
      type: https
      scheme: basic